# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.16
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: sarajanedeveloper@gmail.com
author_name: SaraJane
cloud_provider: none
contract_name: CitrusSwap
preset_name: production
project_name: citrus_swap

